insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (1, 'Amil Lean', 'LA Police Department', '2021/01/10', 80, 70);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (2, 'Titus Pescud', 'LA Police Department', '2020/10/04', 3, 79);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (3, 'Tobin Domeney', 'LA Police Department', '2021/10/22', 41, 32);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (4, 'Isidro Druitt', 'New York Police Department', '2021/02/27', 23, 120);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (5, 'Hakim Grandin', 'Boston Police Department', '2020/10/08', 37, 97);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (6, 'Aldridge Marjanovic', 'New York Police Department', '2020/05/17', 47, 21);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (7, 'Shannen Achurch', 'Miami Police Department', '2021/04/11', 69, 75);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (8, 'Rivi Challens', 'Miami Police Department', '2020/10/13', 41, 44);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (9, 'Petronille Maling', 'Boston Police Department', '2020/09/23', 70, 108);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (10, 'Jenifer Alexis', 'Boston Police Department', '2021/10/20', 64, 106);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (11, 'Joane Paver', 'Boston Police Department', '2021/04/18', 79, 107);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (12, 'Mildred Tuiller', 'Boston Police Department', '2021/09/20', 55, 95);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (13, 'Germaine Dregan', 'Miami Police Department', '2020/12/29', 45, 53);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (14, 'Rowland Rottger', 'New York Police Department', '2020/01/26', 79, 115);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (15, 'Skip Berardt', 'Boston Police Department', '2020/12/02', 54, 81);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (16, 'Ari Essex', 'Boston Police Department', '2020/08/29', 12, 73);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (17, 'Aubree Dufer', 'Boston Police Department', '2021/01/03', 68, 91);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (18, 'Petunia Maasze', 'LA Police Department', '2021/10/08', 74, 68);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (19, 'Laurie Cotelard', 'Miami Police Department', '2021/03/22', 45, 9);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (20, 'Dar Emney', 'New York Police Department', '2020/02/21', 21, 129);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (21, 'Dorotea Jessop', 'New York Police Department', '2020/05/20', 62, 139);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (22, 'Garland Pittaway', 'LA Police Department', '2020/09/11', 14, 56);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (23, 'Paddie Sellar', 'Miami Police Department', '2021/06/26', 55, 91);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (24, 'Coraline Giffen', 'New York Police Department', '2020/01/14', 71, 138);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (25, 'Isaiah Moyne', 'Miami Police Department', '2020/10/09', 87, 91);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (26, 'Candida Arundell', 'LA Police Department', '2021/02/25', 46, 88);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (27, 'Ty Mechic', 'Boston Police Department', '2021/06/24', 79, 121);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (28, 'Myca Druery', 'LA Police Department', '2020/06/21', 82, 37);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (29, 'Hayden Roddick', 'New York Police Department', '2020/03/16', 1, 24);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (30, 'Elvin Selwood', 'New York Police Department', '2020/10/04', 17, 112);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (31, 'Paulita Aldren', 'New York Police Department', '2020/05/18', 34, 6);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (32, 'Kora Beggan', 'LA Police Department', '2021/06/03', 43, 28);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (33, 'Casandra Waldrum', 'LA Police Department', '2021/11/15', 76, 112);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (34, 'Courtnay Lux', 'New York Police Department', '2021/01/12', 45, 121);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (35, 'Ines Jolley', 'LA Police Department', '2020/08/15', 19, 70);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (36, 'Gordy Morsley', 'Miami Police Department', '2020/01/03', 67, 62);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (37, 'Kerrill Garnett', 'New York Police Department', '2021/01/09', 14, 3);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (38, 'Davey Colleford', 'New York Police Department', '2020/05/07', 59, 6);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (39, 'Cash Golling', 'New York Police Department', '2020/11/16', 77, 15);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (40, 'Rebe Joinsey', 'New York Police Department', '2021/07/04', 47, 118);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (41, 'Zacharias Ronisch', 'Miami Police Department', '2022/01/01', 79, 118);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (42, 'Chiquita Siddle', 'LA Police Department', '2021/07/11', 20, 95);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (43, 'Elbertina Alvaro', 'Miami Police Department', '2020/12/13', 35, 116);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (44, 'Chet Dunseath', 'New York Police Department', '2021/09/14', 29, 101);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (45, 'Jock McNeillie', 'New York Police Department', '2020/01/02', 35, 18);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (46, 'Orlan Ketcher', 'Miami Police Department', '2020/08/24', 47, 42);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (47, 'Eada Hambidge', 'Miami Police Department', '2021/05/23', 54, 111);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (48, 'Grannie Igonet', 'Miami Police Department', '2021/09/15', 21, 108);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (49, 'Mortimer Laurentino', 'Miami Police Department', '2020/10/24', 61, 19);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (50, 'Giorgi Penylton', 'Miami Police Department', '2020/05/08', 64, 110);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (51, 'Coralie Warriner', 'New York Police Department', '2021/03/03', 29, 68);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (52, 'Germain Redferne', 'LA Police Department', '2021/11/12', 76, 38);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (53, 'Kalie Crowson', 'New York Police Department', '2021/07/17', 6, 24);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (54, 'Thomasine Myford', 'LA Police Department', '2020/06/18', 12, 39);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (55, 'Lari Lockner', 'Boston Police Department', '2021/07/23', 13, 100);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (56, 'Hayden Grahl', 'New York Police Department', '2020/12/18', 1, 69);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (57, 'Yuri Licciardi', 'Miami Police Department', '2021/10/03', 78, 59);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (58, 'Charles Eggins', 'New York Police Department', '2021/01/05', 43, 40);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (59, 'Marie-jeanne Springthorp', 'LA Police Department', '2021/08/23', 41, 68);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (60, 'Richie Snugg', 'New York Police Department', '2021/04/14', 88, 88);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (61, 'Marje Colchett', 'Boston Police Department', '2021/01/09', 49, 50);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (62, 'Hedvige Grasser', 'New York Police Department', '2020/11/02', 82, 45);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (63, 'Winslow Fronczak', 'Miami Police Department', '2021/08/05', 87, 1);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (64, 'Lauren Kift', 'LA Police Department', '2021/09/27', 84, 67);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (65, 'Alva Longmaid', 'Boston Police Department', '2021/08/19', 19, 113);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (66, 'Conny Raiment', 'LA Police Department', '2021/03/26', 23, 40);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (67, 'Marge Igo', 'Boston Police Department', '2021/10/24', 7, 60);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (68, 'Valle Debling', 'Miami Police Department', '2020/11/14', 62, 22);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (69, 'Jeanine Filby', 'Miami Police Department', '2020/04/14', 55, 104);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (70, 'Kassie Gatehouse', 'Miami Police Department', '2020/07/27', 13, 14);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (71, 'Shaughn Lottrington', 'Boston Police Department', '2020/07/09', 52, 67);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (72, 'Slade Hamsley', 'Miami Police Department', '2021/06/30', 70, 132);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (73, 'Boyce Hassan', 'LA Police Department', '2021/02/20', 3, 56);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (74, 'Kalil Pike', 'New York Police Department', '2020/12/02', 81, 105);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (75, 'Ephraim Paterno', 'LA Police Department', '2021/11/23', 70, 52);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (76, 'Rayshell Gosney', 'LA Police Department', '2021/08/02', 30, 102);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (77, 'Archibold Beining', 'LA Police Department', '2020/09/26', 13, 135);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (78, 'Heriberto Fourman', 'Boston Police Department', '2020/02/14', 84, 107);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (79, 'Lorelle Tustin', 'Miami Police Department', '2021/11/02', 54, 38);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (80, 'Guendolen Okenden', 'LA Police Department', '2020/04/29', 31, 119);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (81, 'Harley Collingdon', 'New York Police Department', '2020/01/19', 74, 48);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (82, 'Faber Langstone', 'Boston Police Department', '2021/05/02', 42, 45);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (83, 'Malinda Stapley', 'LA Police Department', '2021/09/04', 27, 110);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (84, 'Sebastian Kraut', 'LA Police Department', '2020/10/19', 62, 59);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (85, 'Yevette Molloy', 'Miami Police Department', '2021/06/22', 90, 97);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (86, 'Aleksandr Nickolls', 'LA Police Department', '2021/04/30', 66, 2);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (87, 'Glynnis Gravell', 'Boston Police Department', '2020/03/03', 90, 106);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (88, 'Brody Vasyanin', 'Miami Police Department', '2022/01/02', 86, 58);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (89, 'Theodore Onthank', 'Boston Police Department', '2021/12/24', 78, 72);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (90, 'Dalenna Brumfitt', 'LA Police Department', '2020/01/07', 30, 47);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (91, 'Kevina Yorkston', 'New York Police Department', '2021/11/09', 23, 135);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (92, 'Meryl Hardiman', 'New York Police Department', '2021/07/03', 56, 5);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (93, 'Lane Arcase', 'Miami Police Department', '2021/05/30', 14, 69);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (94, 'Allison Luparti', 'Boston Police Department', '2020/03/20', 44, 65);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (95, 'Norine Rigler', 'Boston Police Department', '2021/06/04', 46, 28);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (96, 'Alf Pieroni', 'LA Police Department', '2020/05/26', 25, 44);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (97, 'Hailee Rosle', 'LA Police Department', '2020/05/27', 6, 9);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (98, 'Marie Mattaser', 'LA Police Department', '2020/07/04', 87, 46);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (99, 'Fern Bateman', 'New York Police Department', '2021/02/19', 84, 38);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (100, 'Karlotte Linnit', 'New York Police Department', '2020/08/23', 49, 114);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (101, 'Bette-ann Stood', 'Boston Police Department', '2021/08/02', 17, 111);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (102, 'Lorianne Tallquist', 'Miami Police Department', '2020/04/28', 22, 136);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (103, 'Louie Ropp', 'New York Police Department', '2021/12/23', 35, 128);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (104, 'Minette Andino', 'New York Police Department', '2020/10/31', 6, 105);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (105, 'Gretchen Waplinton', 'New York Police Department', '2020/04/28', 51, 32);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (106, 'Brandie June', 'LA Police Department', '2021/02/23', 2, 112);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (107, 'Ashla Kynoch', 'Miami Police Department', '2020/05/13', 46, 30);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (108, 'Willyt Paramore', 'LA Police Department', '2021/05/24', 11, 91);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (109, 'Olympia Brownlie', 'New York Police Department', '2020/04/21', 52, 99);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (110, 'Hillary Tredget', 'Boston Police Department', '2021/02/05', 46, 80);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (111, 'Fern Smyth', 'Boston Police Department', '2020/01/18', 69, 138);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (112, 'Haskell Winscum', 'New York Police Department', '2020/08/09', 86, 60);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (113, 'Toby Tickner', 'New York Police Department', '2020/12/26', 85, 140);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (114, 'Gilda Shearmer', 'LA Police Department', '2020/09/24', 10, 137);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (115, 'Peyter Cheasman', 'LA Police Department', '2021/06/19', 26, 66);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (116, 'Gratia Brader', 'Miami Police Department', '2020/08/22', 26, 66);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (117, 'Boris Makinson', 'Boston Police Department', '2020/08/14', 75, 82);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (118, 'Glennie Luetchford', 'New York Police Department', '2021/05/30', 37, 21);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (119, 'Barnebas Ibberson', 'New York Police Department', '2020/04/05', 74, 90);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (120, 'Linc Ellam', 'New York Police Department', '2020/03/29', 4, 89);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (121, 'Benn Lourenco', 'Miami Police Department', '2021/12/24', 11, 116);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (122, 'Alane Gladdifh', 'Boston Police Department', '2020/08/21', 64, 44);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (123, 'Arlette Rearie', 'Miami Police Department', '2021/05/12', 64, 108);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (124, 'Adena Conachie', 'LA Police Department', '2020/02/08', 62, 130);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (125, 'Lexi Altofts', 'LA Police Department', '2021/10/26', 87, 97);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (126, 'Romeo Pandie', 'LA Police Department', '2021/02/07', 72, 118);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (127, 'Coretta Veneur', 'Boston Police Department', '2020/01/23', 47, 110);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (128, 'Vaughn Ofener', 'LA Police Department', '2021/02/08', 4, 133);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (129, 'Kendra Bruckmann', 'Boston Police Department', '2021/01/14', 59, 94);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (130, 'Kearney Sayward', 'Boston Police Department', '2021/08/05', 58, 104);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (131, 'Yance Mouth', 'New York Police Department', '2020/01/26', 77, 65);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (132, 'Jedediah Dacey', 'Boston Police Department', '2020/09/23', 29, 21);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (133, 'Raquela Punter', 'Miami Police Department', '2020/10/31', 59, 100);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (134, 'Melitta Slavin', 'New York Police Department', '2020/08/22', 2, 97);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (135, 'Violet Birdall', 'LA Police Department', '2020/07/03', 79, 17);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (136, 'Jessalyn Episcopi', 'Miami Police Department', '2020/06/09', 8, 5);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (137, 'Teirtza Hodcroft', 'Boston Police Department', '2020/06/09', 13, 92);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (138, 'Agata Prestland', 'LA Police Department', '2021/09/26', 23, 68);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (139, 'Editha Aleksandrov', 'Miami Police Department', '2020/09/03', 51, 134);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (140, 'Bethina Gerrie', 'Miami Police Department', '2020/04/05', 77, 69);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (141, 'Inglis Bantock', 'Miami Police Department', '2020/01/07', 58, 40);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (142, 'Elliott Delany', 'New York Police Department', '2021/04/02', 61, 100);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (143, 'Devland Sempill', 'New York Police Department', '2021/12/28', 64, 119);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (144, 'Orelie Simononsky', 'Boston Police Department', '2020/01/03', 65, 39);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (145, 'Marijo Pohlke', 'New York Police Department', '2020/06/11', 40, 42);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (146, 'Leona Crowder', 'Miami Police Department', '2020/07/11', 42, 136);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (147, 'Joshuah O''Fielly', 'New York Police Department', '2021/03/22', 22, 89);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (148, 'Marcia Udy', 'LA Police Department', '2021/02/06', 35, 40);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (149, 'Saundra Dummett', 'LA Police Department', '2020/10/19', 81, 51);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (150, 'Israel Aldred', 'New York Police Department', '2021/05/24', 68, 62);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (151, 'Fabien Kinkade', 'Boston Police Department', '2021/05/30', 61, 107);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (152, 'Kelcey Kirtland', 'New York Police Department', '2020/12/25', 43, 115);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (153, 'Tris Corben', 'Boston Police Department', '2020/11/11', 12, 48);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (154, 'Neddie Bowller', 'Boston Police Department', '2020/09/05', 42, 77);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (155, 'Gwendolin Flowerdew', 'New York Police Department', '2021/11/11', 18, 103);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (156, 'Reginauld Rawstron', 'Miami Police Department', '2021/03/01', 70, 22);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (157, 'Gwendolin Hush', 'LA Police Department', '2020/02/03', 28, 55);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (158, 'Daryl Wiggans', 'LA Police Department', '2020/12/17', 2, 40);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (159, 'Norina Prestland', 'Miami Police Department', '2020/03/12', 82, 109);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (160, 'Odella Batchelor', 'Boston Police Department', '2020/09/26', 76, 109);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (161, 'Ryun Salsberg', 'LA Police Department', '2021/07/08', 14, 35);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (162, 'Phillida Raftery', 'Miami Police Department', '2021/12/11', 8, 40);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (163, 'Prudy Casebourne', 'New York Police Department', '2020/09/28', 80, 2);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (164, 'Avigdor Spracklin', 'Miami Police Department', '2021/12/01', 64, 95);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (165, 'Diana Woolatt', 'Miami Police Department', '2020/06/18', 57, 18);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (166, 'Maryanna Kimbly', 'LA Police Department', '2021/10/06', 4, 97);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (167, 'Rosalie Simison', 'LA Police Department', '2021/03/20', 29, 98);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (168, 'Lissy Rait', 'Boston Police Department', '2021/08/23', 5, 55);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (169, 'Gussie Fleming', 'Boston Police Department', '2021/09/02', 47, 29);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (170, 'Deny Hudless', 'LA Police Department', '2020/11/15', 27, 41);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (171, 'Shellysheldon Scown', 'LA Police Department', '2020/07/16', 41, 17);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (172, 'Chandal Bancroft', 'Boston Police Department', '2021/07/13', 41, 22);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (173, 'Renault O''Longain', 'LA Police Department', '2020/09/17', 73, 46);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (174, 'Clarence Darth', 'LA Police Department', '2021/05/27', 57, 45);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (175, 'Waldemar Mole', 'Miami Police Department', '2020/10/27', 36, 45);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (176, 'Trefor Abels', 'Miami Police Department', '2020/01/26', 59, 44);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (177, 'Valdemar Klimochkin', 'LA Police Department', '2021/06/13', 32, 14);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (178, 'Gardiner Chaffer', 'New York Police Department', '2021/07/06', 7, 114);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (179, 'Alene Corneil', 'LA Police Department', '2021/02/07', 45, 25);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (180, 'Aubrey Borrow', 'Boston Police Department', '2021/02/10', 25, 66);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (181, 'Waylan Dursley', 'Boston Police Department', '2020/12/15', 41, 4);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (182, 'Jarrad Stuttard', 'Boston Police Department', '2021/12/11', 36, 33);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (183, 'Florentia Glassopp', 'Boston Police Department', '2020/08/14', 41, 66);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (184, 'Randa Kings', 'LA Police Department', '2020/06/10', 34, 25);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (185, 'Karlee Crielly', 'New York Police Department', '2020/10/06', 27, 15);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (186, 'Garrett Deave', 'LA Police Department', '2020/03/26', 66, 138);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (187, 'Carmel Philbrick', 'Miami Police Department', '2021/08/10', 37, 91);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (188, 'Tommy Coley', 'LA Police Department', '2020/07/01', 27, 7);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (189, 'Pollyanna Todd', 'New York Police Department', '2020/03/13', 16, 67);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (190, 'Shelby Deaves', 'New York Police Department', '2021/08/05', 12, 48);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (191, 'Brennan Kemetz', 'Miami Police Department', '2021/07/25', 46, 123);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (192, 'Loralyn Murtimer', 'Miami Police Department', '2021/08/26', 83, 63);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (193, 'Tim Kerans', 'LA Police Department', '2020/02/24', 65, 92);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (194, 'Brice Brittan', 'Boston Police Department', '2021/03/06', 90, 62);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (195, 'Stepha Maund', 'LA Police Department', '2021/04/01', 57, 6);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (196, 'Andreana Di Bernardo', 'Boston Police Department', '2020/07/12', 83, 54);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (197, 'Willem Dwyer', 'Miami Police Department', '2020/07/04', 44, 13);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (198, 'Lettie Grimsdell', 'LA Police Department', '2020/07/20', 13, 114);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (199, 'Hastings Laminman', 'LA Police Department', '2020/03/06', 37, 69);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, evidence_id) values (200, 'Burlie Spinige', 'Boston Police Department', '2020/03/09', 42, 108);
