insert into simple (id, evidence_name, type, parent_complex) values (1, 'Asteraceae', 'Text message', 65);
insert into simple (id, evidence_name, type, parent_complex) values (2, 'Boraginaceae', 'Photo', 54);
insert into simple (id, evidence_name, type, parent_complex) values (3, 'Poaceae', 'Text message', 95);
insert into simple (id, evidence_name, type, parent_complex) values (4, 'Rubiaceae', 'Photo', 38);
insert into simple (id, evidence_name, type, parent_complex) values (5, 'Polypodiaceae', 'Memo', 29);
insert into simple (id, evidence_name, type, parent_complex) values (6, 'Scrophulariaceae', 'Photo', 26);
insert into simple (id, evidence_name, type, parent_complex) values (7, 'Polemoniaceae', 'Text message', 25);
insert into simple (id, evidence_name, type, parent_complex) values (8, 'Rosaceae', 'Text message', 72);
insert into simple (id, evidence_name, type, parent_complex) values (9, 'Fabaceae', 'Memo', 96);
insert into simple (id, evidence_name, type, parent_complex) values (10, 'Fabaceae', 'Photo', 6);
insert into simple (id, evidence_name, type, parent_complex) values (11, 'Iridaceae', 'Photo', 8);
insert into simple (id, evidence_name, type, parent_complex) values (12, 'Scrophulariaceae', 'Memo', 49);
insert into simple (id, evidence_name, type, parent_complex) values (13, 'Solanaceae', 'Text message', 62);
insert into simple (id, evidence_name, type, parent_complex) values (14, 'Saxifragaceae', 'Text message', null);
insert into simple (id, evidence_name, type, parent_complex) values (15, 'Asteraceae', 'Text message', 84);
insert into simple (id, evidence_name, type, parent_complex) values (16, 'Plumbaginaceae', 'Memo', 91);
insert into simple (id, evidence_name, type, parent_complex) values (17, 'Asteraceae', 'Photo', 59);
insert into simple (id, evidence_name, type, parent_complex) values (18, 'Brassicaceae', 'Memo', 78);
insert into simple (id, evidence_name, type, parent_complex) values (19, 'Fabaceae', 'Photo', 83);
insert into simple (id, evidence_name, type, parent_complex) values (20, 'Ophioglossaceae', 'Photo', 18);
insert into simple (id, evidence_name, type, parent_complex) values (21, 'Asteraceae', 'Text message', 33);
insert into simple (id, evidence_name, type, parent_complex) values (22, 'Sarraceniaceae', 'Photo', 20);
insert into simple (id, evidence_name, type, parent_complex) values (23, 'Seligeriaceae', 'Text message', 52);
insert into simple (id, evidence_name, type, parent_complex) values (24, 'Fabaceae', 'Photo', 92);
insert into simple (id, evidence_name, type, parent_complex) values (25, 'Polemoniaceae', 'Photo', 90);
insert into simple (id, evidence_name, type, parent_complex) values (26, 'Portulacaceae', 'Memo', 99);
insert into simple (id, evidence_name, type, parent_complex) values (27, 'Apiaceae', 'Memo', 57);
insert into simple (id, evidence_name, type, parent_complex) values (28, 'Pteridaceae', 'Memo', 91);
insert into simple (id, evidence_name, type, parent_complex) values (29, 'Poaceae', 'Memo', 3);
insert into simple (id, evidence_name, type, parent_complex) values (30, 'Rosaceae', 'Memo', 25);
insert into simple (id, evidence_name, type, parent_complex) values (31, 'Liliaceae', 'Memo', 65);
insert into simple (id, evidence_name, type, parent_complex) values (32, 'Arthoniaceae', 'Text message', 56);
insert into simple (id, evidence_name, type, parent_complex) values (33, 'Boraginaceae', 'Photo', 44);
insert into simple (id, evidence_name, type, parent_complex) values (34, 'Asteraceae', 'Text message', 78);
insert into simple (id, evidence_name, type, parent_complex) values (35, 'Asteraceae', 'Photo', 48);
insert into simple (id, evidence_name, type, parent_complex) values (36, 'Juncaceae', 'Memo', 62);
insert into simple (id, evidence_name, type, parent_complex) values (37, 'Orchidaceae', 'Photo', 80);
insert into simple (id, evidence_name, type, parent_complex) values (38, 'Poaceae', 'Text message', 55);
insert into simple (id, evidence_name, type, parent_complex) values (39, 'Fabaceae', 'Memo', 9);
insert into simple (id, evidence_name, type, parent_complex) values (40, 'Boraginaceae', 'Photo', 82);
insert into simple (id, evidence_name, type, parent_complex) values (41, 'Fabaceae', 'Memo', 64);
insert into simple (id, evidence_name, type, parent_complex) values (42, 'Polygalaceae', 'Memo', 54);
insert into simple (id, evidence_name, type, parent_complex) values (43, 'Grimmiaceae', 'Memo', 92);
insert into simple (id, evidence_name, type, parent_complex) values (44, 'Liliaceae', 'Text message', 25);
insert into simple (id, evidence_name, type, parent_complex) values (45, 'Solanaceae', 'Memo', 84);
insert into simple (id, evidence_name, type, parent_complex) values (46, 'Betulaceae', 'Text message', 23);
insert into simple (id, evidence_name, type, parent_complex) values (47, 'Brassicaceae', 'Text message', 57);
insert into simple (id, evidence_name, type, parent_complex) values (48, 'Caryophyllaceae', 'Memo', 1);
insert into simple (id, evidence_name, type, parent_complex) values (49, 'Asteraceae', 'Text message', 52);
insert into simple (id, evidence_name, type, parent_complex) values (50, 'Scrophulariaceae', 'Memo', null);
insert into simple (id, evidence_name, type, parent_complex) values (51, 'Campanulaceae', 'Photo', 10);
insert into simple (id, evidence_name, type, parent_complex) values (52, 'Asteraceae', 'Photo', 79);
insert into simple (id, evidence_name, type, parent_complex) values (53, 'Amblystegiaceae', 'Memo', 46);
insert into simple (id, evidence_name, type, parent_complex) values (54, 'Caryophyllaceae', 'Memo', 95);
insert into simple (id, evidence_name, type, parent_complex) values (55, 'Poaceae', 'Memo', 90);
insert into simple (id, evidence_name, type, parent_complex) values (56, 'Orchidaceae', 'Text message', 73);
insert into simple (id, evidence_name, type, parent_complex) values (57, 'Fontinalaceae', 'Photo', 35);
insert into simple (id, evidence_name, type, parent_complex) values (58, 'Apiaceae', 'Photo', 31);
insert into simple (id, evidence_name, type, parent_complex) values (59, 'Caryophyllaceae', 'Photo', 17);
insert into simple (id, evidence_name, type, parent_complex) values (60, 'Polypodiaceae', 'Photo', 81);
insert into simple (id, evidence_name, type, parent_complex) values (61, 'Rosaceae', 'Photo', 27);
insert into simple (id, evidence_name, type, parent_complex) values (62, 'Myrtaceae', 'Memo', 41);
insert into simple (id, evidence_name, type, parent_complex) values (63, 'Gentianaceae', 'Text message', 93);
insert into simple (id, evidence_name, type, parent_complex) values (64, 'Scrophulariaceae', 'Memo', 19);
insert into simple (id, evidence_name, type, parent_complex) values (65, 'Asteraceae', 'Photo', 97);
insert into simple (id, evidence_name, type, parent_complex) values (66, 'Primulaceae', 'Photo', 65);
insert into simple (id, evidence_name, type, parent_complex) values (67, 'Campanulaceae', 'Photo', 90);
insert into simple (id, evidence_name, type, parent_complex) values (68, 'Asteraceae', 'Photo', 55);
insert into simple (id, evidence_name, type, parent_complex) values (69, 'Sarraceniaceae', 'Text message', 55);
insert into simple (id, evidence_name, type, parent_complex) values (70, 'Sphagnaceae', 'Photo', 2);
insert into simple (id, evidence_name, type, parent_complex) values (71, 'Polygonaceae', 'Photo', 89);
insert into simple (id, evidence_name, type, parent_complex) values (72, 'Fabaceae', 'Text message', 4);
insert into simple (id, evidence_name, type, parent_complex) values (73, 'Cyperaceae', 'Text message', 8);
insert into simple (id, evidence_name, type, parent_complex) values (74, 'Fabaceae', 'Memo', 75);
insert into simple (id, evidence_name, type, parent_complex) values (75, 'Rosaceae', 'Memo', 22);
insert into simple (id, evidence_name, type, parent_complex) values (76, 'Liliaceae', 'Photo', null);
insert into simple (id, evidence_name, type, parent_complex) values (77, 'Scrophulariaceae', 'Photo', 51);
insert into simple (id, evidence_name, type, parent_complex) values (78, 'Cyperaceae', 'Text message', 69);
insert into simple (id, evidence_name, type, parent_complex) values (79, 'Crassulaceae', 'Text message', 78);
insert into simple (id, evidence_name, type, parent_complex) values (80, 'Portulacaceae', 'Photo', 43);
insert into simple (id, evidence_name, type, parent_complex) values (81, 'Onagraceae', 'Memo', null);
insert into simple (id, evidence_name, type, parent_complex) values (82, 'Crassulaceae', 'Memo', 21);
insert into simple (id, evidence_name, type, parent_complex) values (83, 'Euphorbiaceae', 'Text message', 56);
insert into simple (id, evidence_name, type, parent_complex) values (84, 'Vittariaceae', 'Text message', 90);
insert into simple (id, evidence_name, type, parent_complex) values (85, 'Porpidiaceae', 'Photo', 6);
insert into simple (id, evidence_name, type, parent_complex) values (86, 'Asteraceae', 'Memo', 77);
insert into simple (id, evidence_name, type, parent_complex) values (87, 'Cactaceae', 'Text message', 66);
insert into simple (id, evidence_name, type, parent_complex) values (88, 'Onagraceae', 'Memo', 65);
insert into simple (id, evidence_name, type, parent_complex) values (89, 'Rosaceae', 'Photo', null);
insert into simple (id, evidence_name, type, parent_complex) values (90, 'Fabaceae', 'Text message', 87);
insert into simple (id, evidence_name, type, parent_complex) values (91, 'Acanthaceae', 'Memo', 96);
insert into simple (id, evidence_name, type, parent_complex) values (92, 'Brassicaceae', 'Text message', 31);
insert into simple (id, evidence_name, type, parent_complex) values (93, 'Brassicaceae', 'Photo', 49);
insert into simple (id, evidence_name, type, parent_complex) values (94, 'Pteridaceae', 'Text message', 41);
insert into simple (id, evidence_name, type, parent_complex) values (95, 'Asteraceae', 'Memo', 62);
insert into simple (id, evidence_name, type, parent_complex) values (96, 'Aspleniaceae', 'Photo', null);
insert into simple (id, evidence_name, type, parent_complex) values (97, 'Poaceae', 'Text message', 93);
insert into simple (id, evidence_name, type, parent_complex) values (98, 'Asteraceae', 'Text message', 5);
insert into simple (id, evidence_name, type, parent_complex) values (99, 'Cyperaceae', 'Photo', 64);
insert into simple (id, evidence_name, type, parent_complex) values (100, 'Rosaceae', 'Text message', 38);
insert into simple (id, evidence_name, type, parent_complex) values (101, 'Thymelaeaceae', 'Photo', null);
insert into simple (id, evidence_name, type, parent_complex) values (102, 'Apiaceae', 'Memo', 77);
insert into simple (id, evidence_name, type, parent_complex) values (103, 'Begoniaceae', 'Memo', 74);
insert into simple (id, evidence_name, type, parent_complex) values (104, 'Polemoniaceae', 'Text message', 62);
insert into simple (id, evidence_name, type, parent_complex) values (105, 'Rhamnaceae', 'Memo', 5);
insert into simple (id, evidence_name, type, parent_complex) values (106, 'Polemoniaceae', 'Text message', 46);
insert into simple (id, evidence_name, type, parent_complex) values (107, 'Uncertain Ascomycota Family', 'Text message', 42);
insert into simple (id, evidence_name, type, parent_complex) values (108, 'Poaceae', 'Memo', 22);
insert into simple (id, evidence_name, type, parent_complex) values (109, 'Portulacaceae', 'Memo', 25);
insert into simple (id, evidence_name, type, parent_complex) values (110, 'Polemoniaceae', 'Photo', 18);
insert into simple (id, evidence_name, type, parent_complex) values (111, 'Nephromataceae', 'Photo', 46);
insert into simple (id, evidence_name, type, parent_complex) values (112, 'Rosaceae', 'Photo', 26);
insert into simple (id, evidence_name, type, parent_complex) values (113, 'Papaveraceae', 'Memo', 40);
insert into simple (id, evidence_name, type, parent_complex) values (114, 'Rosaceae', 'Text message', 59);
insert into simple (id, evidence_name, type, parent_complex) values (115, 'Onagraceae', 'Text message', 9);
insert into simple (id, evidence_name, type, parent_complex) values (116, 'Boraginaceae', 'Text message', 96);
insert into simple (id, evidence_name, type, parent_complex) values (117, 'Sabiaceae', 'Photo', 21);
insert into simple (id, evidence_name, type, parent_complex) values (118, 'Juncaceae', 'Photo', 4);
insert into simple (id, evidence_name, type, parent_complex) values (119, 'Lamiaceae', 'Photo', 70);
insert into simple (id, evidence_name, type, parent_complex) values (120, 'Hypnaceae', 'Memo', 76);
