insert into simple (id, type) values (1, 'Voice Memo');
insert into simple (id, type) values (2, 'Physical object');
insert into simple (id, type) values (3, 'Photo');
insert into simple (id, type) values (4, 'Physical object');
insert into simple (id, type) values (5, 'Photo');
insert into simple (id, type) values (6, 'Voice Memo');
insert into simple (id, type) values (7, 'Voice Memo');
insert into simple (id, type) values (8, 'Text Message');
insert into simple (id, type) values (9, 'Photo');
insert into simple (id, type) values (10, 'Photo');
insert into simple (id, type) values (11, 'Text Message');
insert into simple (id, type) values (12, 'Photo');
insert into simple (id, type) values (13, 'Physical object');
insert into simple (id, type) values (14, 'Physical object');
insert into simple (id, type) values (15, 'Text Message');
insert into simple (id, type) values (16, 'Voice Memo');
insert into simple (id, type) values (17, 'Photo');
insert into simple (id, type) values (18, 'Physical object');
insert into simple (id, type) values (19, 'Photo');
insert into simple (id, type) values (20, 'Physical object');
insert into simple (id, type) values (21, 'Text Message');
insert into simple (id, type) values (22, 'Voice Memo');
insert into simple (id, type) values (23, 'Text Message');
insert into simple (id, type) values (24, 'Voice Memo');
insert into simple (id, type) values (25, 'Voice Memo');
insert into simple (id, type) values (26, 'Physical object');
insert into simple (id, type) values (27, 'Photo');
insert into simple (id, type) values (28, 'Voice Memo');
insert into simple (id, type) values (29, 'Photo');
insert into simple (id, type) values (30, 'Photo');
insert into simple (id, type) values (31, 'Voice Memo');
insert into simple (id, type) values (32, 'Photo');
insert into simple (id, type) values (33, 'Text Message');
insert into simple (id, type) values (34, 'Physical object');
insert into simple (id, type) values (35, 'Voice Memo');
insert into simple (id, type) values (36, 'Voice Memo');
insert into simple (id, type) values (37, 'Physical object');
insert into simple (id, type) values (38, 'Text Message');
insert into simple (id, type) values (39, 'Text Message');
insert into simple (id, type) values (40, 'Photo');
insert into simple (id, type) values (41, 'Text Message');
insert into simple (id, type) values (42, 'Photo');
insert into simple (id, type) values (43, 'Text Message');
insert into simple (id, type) values (44, 'Photo');
insert into simple (id, type) values (45, 'Physical object');
insert into simple (id, type) values (46, 'Photo');
insert into simple (id, type) values (47, 'Voice Memo');
insert into simple (id, type) values (48, 'Physical object');
insert into simple (id, type) values (49, 'Physical object');
insert into simple (id, type) values (50, 'Photo');
insert into simple (id, type) values (51, 'Voice Memo');
insert into simple (id, type) values (52, 'Voice Memo');
insert into simple (id, type) values (53, 'Physical object');
insert into simple (id, type) values (54, 'Voice Memo');
insert into simple (id, type) values (55, 'Voice Memo');
insert into simple (id, type) values (56, 'Photo');
insert into simple (id, type) values (57, 'Voice Memo');
insert into simple (id, type) values (58, 'Text Message');
insert into simple (id, type) values (59, 'Photo');
insert into simple (id, type) values (60, 'Physical object');
insert into simple (id, type) values (61, 'Voice Memo');
insert into simple (id, type) values (62, 'Voice Memo');
insert into simple (id, type) values (63, 'Text Message');
insert into simple (id, type) values (64, 'Physical object');
insert into simple (id, type) values (65, 'Text Message');
insert into simple (id, type) values (66, 'Text Message');
insert into simple (id, type) values (67, 'Voice Memo');
insert into simple (id, type) values (68, 'Photo');
insert into simple (id, type) values (69, 'Voice Memo');
insert into simple (id, type) values (70, 'Physical object');
insert into simple (id, type) values (71, 'Physical object');
insert into simple (id, type) values (72, 'Photo');
insert into simple (id, type) values (73, 'Text Message');
insert into simple (id, type) values (74, 'Photo');
insert into simple (id, type) values (75, 'Text Message');
insert into simple (id, type) values (76, 'Photo');
insert into simple (id, type) values (77, 'Physical object');
insert into simple (id, type) values (78, 'Photo');
insert into simple (id, type) values (79, 'Voice Memo');
insert into simple (id, type) values (80, 'Photo');
insert into simple (id, type) values (81, 'Photo');
insert into simple (id, type) values (82, 'Text Message');
insert into simple (id, type) values (83, 'Voice Memo');
insert into simple (id, type) values (84, 'Photo');
insert into simple (id, type) values (85, 'Voice Memo');
insert into simple (id, type) values (86, 'Physical object');
insert into simple (id, type) values (87, 'Text Message');
insert into simple (id, type) values (88, 'Photo');
insert into simple (id, type) values (89, 'Text Message');
insert into simple (id, type) values (90, 'Text Message');
insert into simple (id, type) values (91, 'Text Message');
insert into simple (id, type) values (92, 'Physical object');
insert into simple (id, type) values (93, 'Text Message');
insert into simple (id, type) values (94, 'Text Message');
insert into simple (id, type) values (95, 'Voice Memo');
insert into simple (id, type) values (96, 'Physical object');
insert into simple (id, type) values (97, 'Photo');
insert into simple (id, type) values (98, 'Text Message');
insert into simple (id, type) values (99, 'Physical object');
insert into simple (id, type) values (100, 'Physical object');
insert into simple (id, type) values (101, 'Text Message');
insert into simple (id, type) values (102, 'Text Message');
insert into simple (id, type) values (103, 'Photo');
insert into simple (id, type) values (104, 'Photo');
insert into simple (id, type) values (105, 'Physical object');
insert into simple (id, type) values (106, 'Physical object');
insert into simple (id, type) values (107, 'Text Message');
insert into simple (id, type) values (108, 'Voice Memo');
insert into simple (id, type) values (109, 'Voice Memo');
insert into simple (id, type) values (110, 'Text Message');
insert into simple (id, type) values (111, 'Photo');
insert into simple (id, type) values (112, 'Photo');
insert into simple (id, type) values (113, 'Physical object');
insert into simple (id, type) values (114, 'Voice Memo');
insert into simple (id, type) values (115, 'Photo');
insert into simple (id, type) values (116, 'Photo');
insert into simple (id, type) values (117, 'Text Message');
insert into simple (id, type) values (118, 'Photo');
insert into simple (id, type) values (119, 'Voice Memo');
insert into simple (id, type) values (120, 'Photo');
