insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (1, 'Bobbette Bikker', 'Boston Police Department', '2020/09/19', 16, 48);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (2, 'Madeleine Officer', 'New York Police Department', '2020/06/26', 44, 91);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (3, 'Merle Cherm', 'Boston Police Department', '2021/12/01', 79, 30);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (4, 'Mariquilla Sage', 'Boston Police Department', '2020/04/22', 51, 5);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (5, 'Minny Folomkin', 'New York Police Department', '2020/08/05', 71, 55);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (6, 'Holly-anne Huff', 'New York Police Department', '2020/05/21', 53, 83);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (7, 'Lanie Hayler', 'New York Police Department', '2020/07/29', 54, 63);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (8, 'Joann Orneblow', 'Miami Police Department', '2020/06/21', 81, 66);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (9, 'Colly Franzoli', 'LA Police Department', '2021/11/29', 74, 104);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (10, 'Griswold Bamsey', 'Miami Police Department', '2021/04/26', 41, 43);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (11, 'Lionello Giraldo', 'Miami Police Department', '2020/07/11', 88, 20);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (12, 'Edward Holyard', 'New York Police Department', '2021/12/04', 25, 132);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (13, 'Forester Drakeley', 'New York Police Department', '2021/04/22', 42, 126);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (14, 'Sid Goodlake', 'LA Police Department', '2020/11/22', 59, 19);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (15, 'Anestassia Chaudrelle', 'New York Police Department', '2020/11/25', 58, 41);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (16, 'Tonie Ashfull', 'Boston Police Department', '2021/07/10', 10, 70);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (17, 'Rhiamon Jenk', 'Miami Police Department', '2021/03/15', 29, 52);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (18, 'Tuck Gurg', 'New York Police Department', '2020/01/16', 71, 85);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (19, 'Greer Bethell', 'New York Police Department', '2020/03/14', 73, 66);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (20, 'Deonne Whorton', 'LA Police Department', '2021/04/09', 50, 98);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (21, 'Kayla Mignot', 'Boston Police Department', '2020/02/18', 1, 92);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (22, 'Baxy Dory', 'LA Police Department', '2020/10/01', 52, 112);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (23, 'Waylin Snel', 'Boston Police Department', '2020/10/27', 72, 137);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (24, 'Nesta Laville', 'Boston Police Department', '2021/07/25', 8, 95);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (25, 'Umeko Rush', 'LA Police Department', '2021/06/28', 8, 61);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (26, 'Tiff Gavin', 'Boston Police Department', '2021/12/06', 40, 71);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (27, 'Ellwood Randales', 'Boston Police Department', '2020/05/05', 54, 105);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (28, 'Creigh Louch', 'Miami Police Department', '2021/04/13', 87, 85);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (29, 'Sheena Lysons', 'Boston Police Department', '2021/04/18', 25, 30);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (30, 'Brent Deare', 'Miami Police Department', '2020/02/14', 18, 96);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (31, 'Leelah Peaddie', 'Miami Police Department', '2021/05/26', 51, 72);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (32, 'Jessamyn Marcroft', 'Miami Police Department', '2021/01/04', 2, 16);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (33, 'Khalil Searsby', 'Boston Police Department', '2021/09/02', 46, 14);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (34, 'Sydney Sedworth', 'Boston Police Department', '2020/01/09', 77, 110);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (35, 'Rickert Bussons', 'New York Police Department', '2020/01/09', 86, 47);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (36, 'Doreen Kytley', 'New York Police Department', '2021/12/30', 42, 69);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (37, 'Burke Fishe', 'LA Police Department', '2020/10/05', 57, 79);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (38, 'Melita Titcumb', 'New York Police Department', '2021/02/27', 15, 57);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (39, 'Daveta Zanazzi', 'LA Police Department', '2020/10/18', 14, 41);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (40, 'Wynny Jindracek', 'Miami Police Department', '2020/02/08', 41, 100);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (41, 'Vivian Pinkerton', 'New York Police Department', '2020/10/08', 68, 131);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (42, 'Paige Ishchenko', 'Miami Police Department', '2020/12/15', 44, 90);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (43, 'Leola Houchen', 'Boston Police Department', '2020/07/26', 67, 89);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (44, 'Andra Mervyn', 'LA Police Department', '2020/03/03', 4, 4);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (45, 'Bekki Maestro', 'Boston Police Department', '2021/10/30', 7, 71);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (46, 'Kerr Crouch', 'LA Police Department', '2020/10/10', 16, 124);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (47, 'Bar Dunseath', 'Boston Police Department', '2022/01/01', 15, 67);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (48, 'Hamlin Llewellen', 'Miami Police Department', '2020/05/11', 35, 2);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (49, 'Gayel Pickavance', 'Miami Police Department', '2021/03/02', 40, 39);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (50, 'Neely Tolle', 'New York Police Department', '2021/05/04', 72, 91);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (51, 'Britt Espada', 'Miami Police Department', '2021/03/07', 16, 44);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (52, 'Lavena Brazear', 'New York Police Department', '2021/01/21', 44, 23);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (53, 'Ysabel Hansill', 'Miami Police Department', '2021/01/08', 79, 58);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (54, 'Mathias Saxelby', 'LA Police Department', '2020/09/20', 50, 105);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (55, 'Martelle Liddell', 'LA Police Department', '2021/05/29', 4, 135);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (56, 'Tabby Idale', 'Boston Police Department', '2020/12/04', 45, 28);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (57, 'Alano Rawsthorne', 'LA Police Department', '2020/05/03', 76, 122);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (58, 'Maudie Capehorn', 'LA Police Department', '2020/10/13', 83, 5);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (59, 'Shepperd Ackrill', 'Miami Police Department', '2020/02/12', 27, 76);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (60, 'Sheree Reiners', 'New York Police Department', '2021/05/03', 63, 114);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (61, 'Charyl Ensten', 'New York Police Department', '2020/12/21', 87, 49);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (62, 'Wilt Dehm', 'New York Police Department', '2021/08/29', 54, 117);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (63, 'Falito MacKeig', 'LA Police Department', '2020/09/22', 47, 140);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (64, 'Agustin Rue', 'LA Police Department', '2022/01/02', 85, 129);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (65, 'Audrie Jozwicki', 'Miami Police Department', '2021/04/19', 12, 50);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (66, 'Theda Belleny', 'New York Police Department', '2020/02/12', 44, 41);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (67, 'Zelda Dmitrovic', 'LA Police Department', '2020/03/11', 65, 53);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (68, 'Myrwyn Branscomb', 'New York Police Department', '2021/09/15', 66, 114);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (69, 'Bay Quarton', 'Miami Police Department', '2021/05/18', 46, 20);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (70, 'Emlynne Vynoll', 'New York Police Department', '2020/04/18', 27, 55);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (71, 'Gwenore Christy', 'LA Police Department', '2021/08/04', 4, 19);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (72, 'Garek Camamile', 'LA Police Department', '2020/01/23', 34, 32);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (73, 'Minnaminnie Hambric', 'New York Police Department', '2020/07/10', 37, 45);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (74, 'Pedro Hummerston', 'Miami Police Department', '2020/10/28', 57, 8);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (75, 'Sayre Kinvig', 'Boston Police Department', '2021/06/23', 72, 41);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (76, 'Jory Gumme', 'LA Police Department', '2020/11/01', 86, 115);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (77, 'Ruttger Tanswill', 'LA Police Department', '2021/02/19', 71, 14);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (78, 'Bartie Bransby', 'New York Police Department', '2020/08/19', 69, 59);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (79, 'Reynold Edmondson', 'New York Police Department', '2020/01/19', 58, 139);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (80, 'Thom Fresson', 'New York Police Department', '2021/10/11', 42, 90);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (81, 'Fenelia Stirtle', 'Boston Police Department', '2021/12/22', 46, 113);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (82, 'Gustavus Belton', 'Miami Police Department', '2021/02/03', 18, 95);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (83, 'Elenore Chippindall', 'Boston Police Department', '2020/03/02', 49, 10);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (84, 'Fraser Padwick', 'Miami Police Department', '2020/10/05', 80, 130);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (85, 'Inness Gronowe', 'New York Police Department', '2020/11/01', 58, 6);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (86, 'Alasteir Wanklyn', 'Boston Police Department', '2020/08/14', 84, 139);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (87, 'Cherianne Shedd', 'LA Police Department', '2020/09/14', 53, 83);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (88, 'Raine Bertlin', 'Boston Police Department', '2020/05/27', 79, 120);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (89, 'Nadeen Brien', 'LA Police Department', '2020/02/25', 65, 38);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (90, 'Hertha Lamberts', 'Miami Police Department', '2021/04/18', 34, 2);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (91, 'Grata Finci', 'Boston Police Department', '2020/07/03', 11, 121);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (92, 'Noemi De la Yglesia', 'Boston Police Department', '2021/08/02', 11, 6);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (93, 'Rycca Boland', 'LA Police Department', '2021/05/05', 58, 84);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (94, 'Alena MacKeig', 'LA Police Department', '2021/08/08', 82, 69);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (95, 'Teddi Lechmere', 'Boston Police Department', '2021/12/09', 20, 25);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (96, 'Noella Astin', 'New York Police Department', '2020/10/17', 75, 45);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (97, 'Jehu Vinck', 'Boston Police Department', '2020/11/16', 76, 48);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (98, 'Tricia Juhruke', 'LA Police Department', '2021/04/18', 55, 51);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (99, 'Woodie Schruyers', 'New York Police Department', '2020/12/13', 40, 25);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (100, 'Edward Chatterton', 'Miami Police Department', '2020/09/08', 78, 56);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (101, 'Garrard Dilnot', 'New York Police Department', '2021/05/27', 66, 129);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (102, 'Arabele Haverson', 'LA Police Department', '2021/10/23', 68, 43);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (103, 'Benita Hanstock', 'LA Police Department', '2021/06/08', 40, 76);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (104, 'Nels McPhillips', 'LA Police Department', '2020/03/16', 88, 99);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (105, 'Glennie Chapling', 'Boston Police Department', '2020/08/23', 83, 29);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (106, 'Gus Litchfield', 'New York Police Department', '2020/10/12', 90, 92);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (107, 'Morgen Minifie', 'LA Police Department', '2021/02/26', 21, 113);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (108, 'Esta Fielden', 'LA Police Department', '2021/05/27', 49, 138);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (109, 'Malena Bramhill', 'LA Police Department', '2020/07/08', 47, 39);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (110, 'Donn Waghorn', 'New York Police Department', '2020/10/31', 78, 22);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (111, 'Lamar Steers', 'Miami Police Department', '2021/10/26', 39, 63);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (112, 'Trude Chetwynd', 'Boston Police Department', '2021/10/30', 3, 126);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (113, 'Moishe Blitzer', 'LA Police Department', '2021/06/02', 75, 106);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (114, 'Celestyna Suerz', 'Miami Police Department', '2020/09/27', 26, 109);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (115, 'Pavia Marjoram', 'Boston Police Department', '2020/11/13', 28, 46);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (116, 'Bartholomeo Aubury', 'Miami Police Department', '2020/01/06', 5, 115);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (117, 'Netti Brownfield', 'New York Police Department', '2021/12/25', 90, 111);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (118, 'Ignacius Gott', 'New York Police Department', '2020/01/27', 65, 11);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (119, 'Avie Fernan', 'Boston Police Department', '2020/12/06', 59, 8);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (120, 'Pier Piddletown', 'LA Police Department', '2021/10/23', 26, 128);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (121, 'Nedda Vonderdell', 'New York Police Department', '2020/10/30', 66, 68);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (122, 'Jard McGhie', 'Boston Police Department', '2020/01/25', 39, 56);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (123, 'Baudoin Sim', 'Boston Police Department', '2021/08/28', 80, 134);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (124, 'Timmi Bremond', 'New York Police Department', '2021/03/04', 11, 76);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (125, 'Zaccaria Pavis', 'Miami Police Department', '2021/05/30', 71, 124);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (126, 'Loralie Tummond', 'New York Police Department', '2020/11/05', 49, 126);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (127, 'Ursola Mulderrig', 'Miami Police Department', '2020/09/05', 62, 69);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (128, 'Odelia Gooders', 'LA Police Department', '2020/06/04', 69, 13);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (129, 'Pearce Brimm', 'Miami Police Department', '2021/12/31', 75, 73);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (130, 'Ashlan Vamplew', 'Boston Police Department', '2021/01/10', 81, 73);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (131, 'Doralia Maxsted', 'Miami Police Department', '2020/12/06', 53, 107);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (132, 'Gusty Delong', 'LA Police Department', '2020/05/16', 69, 140);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (133, 'Max Burner', 'LA Police Department', '2020/04/23', 75, 113);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (134, 'Zollie Laxen', 'Miami Police Department', '2021/09/17', 22, 25);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (135, 'Janey Eddins', 'Boston Police Department', '2021/05/11', 41, 8);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (136, 'Ugo Tokley', 'LA Police Department', '2020/02/28', 79, 121);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (137, 'Jonis Hazelton', 'Miami Police Department', '2020/06/06', 70, 24);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (138, 'Tammie Franc', 'Miami Police Department', '2021/09/16', 7, 16);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (139, 'Saxe Ilchuk', 'Boston Police Department', '2020/01/25', 90, 108);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (140, 'Jammie Rentelll', 'LA Police Department', '2020/08/30', 34, 31);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (141, 'Gaultiero Allaker', 'Miami Police Department', '2020/02/23', 87, 8);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (142, 'Sharline Chelsom', 'LA Police Department', '2021/11/05', 60, 116);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (143, 'Bobby Vise', 'Miami Police Department', '2021/05/25', 12, 109);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (144, 'Casey Carrigan', 'Miami Police Department', '2020/07/03', 34, 79);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (145, 'Berty Degg', 'LA Police Department', '2021/06/09', 74, 35);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (146, 'Bryna Geraghty', 'Miami Police Department', '2020/10/14', 76, 25);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (147, 'Magda Haugg', 'LA Police Department', '2021/05/01', 2, 24);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (148, 'Lindy Phipp', 'Boston Police Department', '2022/01/05', 70, 26);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (149, 'Freda Haddy', 'Boston Police Department', '2020/05/14', 83, 132);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (150, 'Susette Ferreiro', 'Miami Police Department', '2021/02/17', 28, 22);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (151, 'Vergil Jeffers', 'Miami Police Department', '2021/08/12', 35, 31);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (152, 'Stinky Stonier', 'LA Police Department', '2021/08/22', 80, 65);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (153, 'Callean Kennelly', 'Miami Police Department', '2021/08/27', 16, 42);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (154, 'Miguela Blitzer', 'LA Police Department', '2021/12/21', 41, 73);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (155, 'Rosina Loosmore', 'New York Police Department', '2020/11/08', 22, 77);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (156, 'Mella Poulden', 'Miami Police Department', '2021/07/27', 13, 49);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (157, 'Korry Kleinschmidt', 'Boston Police Department', '2020/09/22', 19, 130);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (158, 'Esme Daggett', 'New York Police Department', '2021/11/01', 55, 88);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (159, 'Pearl Orlton', 'New York Police Department', '2020/06/17', 32, 97);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (160, 'Rebecka Kunert', 'Miami Police Department', '2021/12/25', 73, 7);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (161, 'Chancey Le Breton De La Vieuville', 'New York Police Department', '2020/04/27', 27, 101);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (162, 'Manolo Farquhar', 'Miami Police Department', '2021/06/07', 44, 40);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (163, 'Toinette Jouhan', 'New York Police Department', '2021/07/19', 23, 68);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (164, 'Gardiner Connachan', 'Boston Police Department', '2021/08/05', 88, 77);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (165, 'Grant Laise', 'Miami Police Department', '2021/06/06', 40, 128);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (166, 'Florida Semrad', 'LA Police Department', '2020/07/01', 77, 127);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (167, 'Justinian Pierrepoint', 'Boston Police Department', '2020/03/14', 21, 37);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (168, 'Trudie Mattiazzo', 'Miami Police Department', '2021/11/16', 55, 113);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (169, 'Christyna Dowsing', 'New York Police Department', '2020/01/10', 29, 42);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (170, 'Doralynn Lutty', 'Boston Police Department', '2021/06/07', 45, 23);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (171, 'Noll Fitchett', 'Boston Police Department', '2020/07/12', 27, 23);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (172, 'Kaleb Howells', 'LA Police Department', '2021/02/25', 37, 41);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (173, 'Orson Pinnegar', 'Miami Police Department', '2021/08/04', 40, 136);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (174, 'Adam Bolam', 'New York Police Department', '2020/08/23', 13, 54);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (175, 'Emmie Clevely', 'Miami Police Department', '2021/04/03', 88, 112);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (176, 'Felipe Durdy', 'Boston Police Department', '2020/11/12', 88, 80);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (177, 'Griffith Capaldo', 'Miami Police Department', '2021/09/03', 70, 72);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (178, 'Gayle Weald', 'LA Police Department', '2020/03/29', 23, 92);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (179, 'Devin Christophle', 'LA Police Department', '2020/07/20', 67, 35);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (180, 'Evey Hollyar', 'Miami Police Department', '2021/02/21', 76, 65);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (181, 'Nevile Duffitt', 'LA Police Department', '2020/04/10', 12, 28);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (182, 'Giacopo Arpino', 'Boston Police Department', '2020/03/28', 43, 128);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (183, 'Kaycee Raith', 'Boston Police Department', '2021/10/25', 33, 124);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (184, 'Raf Dilley', 'Boston Police Department', '2020/03/19', 10, 38);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (185, 'Rickie Blackey', 'New York Police Department', '2020/03/20', 6, 96);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (186, 'Rayner Durie', 'Boston Police Department', '2020/06/20', 22, 135);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (187, 'Erin Rand', 'Boston Police Department', '2021/09/12', 75, 82);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (188, 'Drusilla Fontaine', 'Boston Police Department', '2020/09/30', 24, 84);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (189, 'Conant Beckmann', 'Miami Police Department', '2020/02/13', 79, 98);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (190, 'Drew Stoffel', 'Boston Police Department', '2020/03/28', 69, 131);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (191, 'Rheta Dearnley', 'Boston Police Department', '2021/02/10', 31, 85);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (192, 'Frayda Kirsche', 'Boston Police Department', '2021/04/05', 16, 32);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (193, 'Judy Pickering', 'LA Police Department', '2020/01/28', 42, 86);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (194, 'Bella Tolliday', 'LA Police Department', '2020/01/22', 77, 13);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (195, 'Gabriello Hoogendorp', 'New York Police Department', '2020/06/28', 10, 137);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (196, 'Fabiano Clitheroe', 'Miami Police Department', '2020/04/18', 84, 68);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (197, 'Verile Northwood', 'Boston Police Department', '2021/08/07', 20, 79);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (198, 'Berni Stiger', 'Miami Police Department', '2020/04/07', 64, 95);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (199, 'Roderich Dugget', 'LA Police Department', '2021/11/10', 55, 79);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (200, 'Elsi Birwhistle', 'Boston Police Department', '2020/09/22', 62, 58);
