insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (1, 'Rodge Saur', 'New York Police Department', '2021/01/25', 15, 84);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (2, 'Rip O'' Culligan', 'Boston Police Department', '2020/05/12', 40, 58);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (3, 'Quinton Vaskin', 'Boston Police Department', '2021/09/02', 67, 20);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (4, 'Warde Sybbe', 'LA Police Department', '2020/06/12', 56, 64);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (5, 'Brynn Jesper', 'LA Police Department', '2020/05/23', 40, 2);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (6, 'Lexy Hospital', 'Miami Police Department', '2021/08/25', 7, 89);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (7, 'Del Bradforth', 'Miami Police Department', '2021/01/17', 68, 88);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (8, 'Louisa Itchingham', 'Miami Police Department', '2021/04/27', 22, 80);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (9, 'Arnuad Kildale', 'Miami Police Department', '2020/11/06', 66, 98);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (10, 'Kaycee McGarva', 'LA Police Department', '2020/12/14', 59, 1);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (11, 'Eliot Fleetham', 'LA Police Department', '2020/07/28', 27, 52);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (12, 'Shanta Cobden', 'Boston Police Department', '2020/10/27', 6, 18);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (13, 'Wallie Kayes', 'New York Police Department', '2021/08/10', 65, 81);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (14, 'Brana Klyner', 'Miami Police Department', '2021/10/12', 85, 4);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (15, 'Maura Bartalot', 'LA Police Department', '2020/01/22', 86, 7);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (16, 'Shelagh Gaddas', 'Boston Police Department', '2021/11/20', 38, 12);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (17, 'Rik Heady', 'Boston Police Department', '2021/12/30', 34, 91);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (18, 'Andreana Simmens', 'Miami Police Department', '2021/02/06', 27, 81);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (19, 'Christal Stonard', 'Boston Police Department', '2020/02/04', 19, 37);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (20, 'Tally Kock', 'Miami Police Department', '2020/12/16', 61, 86);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (21, 'Samson Seekings', 'Boston Police Department', '2021/01/24', 63, 48);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (22, 'Kyle Dalgleish', 'New York Police Department', '2020/03/08', 84, 89);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (23, 'Allister Agney', 'New York Police Department', '2021/10/02', 71, 40);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (24, 'Irina Melbury', 'Boston Police Department', '2021/01/19', 56, 62);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (25, 'Claude Castaignet', 'LA Police Department', '2020/08/26', 64, 57);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (26, 'Yelena Pelman', 'Boston Police Department', '2021/01/08', 1, 34);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (27, 'Shadow Frankowski', 'Boston Police Department', '2020/10/09', 64, 35);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (28, 'Rustie Farherty', 'Miami Police Department', '2020/07/05', 24, 25);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (29, 'Caro Gergher', 'Boston Police Department', '2020/04/09', 7, 88);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (30, 'Ailyn Maffiotti', 'LA Police Department', '2020/03/20', 64, 52);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (31, 'Catlin Cars', 'LA Police Department', '2021/12/29', 25, 33);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (32, 'Babita Shreeves', 'Boston Police Department', '2020/01/12', 5, 88);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (33, 'Montgomery Lindblom', 'New York Police Department', '2021/04/29', 12, 19);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (34, 'Henrieta Tait', 'Boston Police Department', '2021/05/29', 47, 1);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (35, 'Carissa Klimp', 'Boston Police Department', '2021/07/19', 74, 83);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (36, 'Lynnette Carding', 'New York Police Department', '2021/07/31', 4, 75);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (37, 'Athena O''Hone', 'LA Police Department', '2020/02/27', 82, 80);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (38, 'Gabey Slyne', 'New York Police Department', '2021/06/04', 77, 62);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (39, 'Jo Canario', 'Boston Police Department', '2020/05/03', 50, 50);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (40, 'Tiphanie Crocumbe', 'Miami Police Department', '2021/11/04', 41, 5);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (41, 'Celesta Kerbey', 'New York Police Department', '2021/04/25', 23, 16);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (42, 'Tobe Kaine', 'New York Police Department', '2021/06/30', 66, 11);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (43, 'Shandy Gibson', 'Boston Police Department', '2021/12/09', 89, 100);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (44, 'Joby Pellington', 'New York Police Department', '2020/03/21', 80, 20);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (45, 'Orsola Cowpland', 'LA Police Department', '2021/10/02', 32, 23);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (46, 'Alfi Pedder', 'New York Police Department', '2021/06/18', 63, 97);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (47, 'Timofei Henricsson', 'New York Police Department', '2020/02/13', 54, 57);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (48, 'Gerty Mennithorp', 'New York Police Department', '2021/09/09', 87, 94);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (49, 'Kirsti Creavin', 'Miami Police Department', '2020/07/25', 45, 92);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (50, 'Lurette Wiffen', 'Boston Police Department', '2020/05/06', 6, 43);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (51, 'Olin Loades', 'Miami Police Department', '2020/01/08', 22, 72);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (52, 'Avigdor Ravenhills', 'New York Police Department', '2020/09/15', 63, 7);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (53, 'Aurelea Jakaway', 'Boston Police Department', '2021/05/12', 31, 50);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (54, 'Bibi Halcro', 'LA Police Department', '2021/09/20', 20, 13);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (55, 'Georas Dautry', 'Boston Police Department', '2020/07/16', 28, 40);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (56, 'Wini Penvarden', 'LA Police Department', '2021/03/29', 80, 88);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (57, 'Ashely Aupol', 'New York Police Department', '2021/10/25', 47, 75);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (58, 'Greg Gilffillan', 'Boston Police Department', '2021/03/03', 25, 74);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (59, 'Yolanthe Orwin', 'New York Police Department', '2020/09/20', 50, 97);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (60, 'Edlin Ullrich', 'Boston Police Department', '2020/10/04', 60, 58);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (61, 'Gusti Walczak', 'Boston Police Department', '2021/09/20', 50, 28);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (62, 'Allard Glyde', 'New York Police Department', '2020/07/17', 78, 7);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (63, 'Nichole Attree', 'Boston Police Department', '2021/03/26', 84, 67);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (64, 'Muire Humes', 'Miami Police Department', '2021/08/23', 34, 7);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (65, 'Ian Brandt', 'Boston Police Department', '2021/09/26', 2, 25);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (66, 'Cordi Northover', 'Miami Police Department', '2020/09/18', 38, 57);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (67, 'Blane Schubert', 'Miami Police Department', '2022/01/04', 17, 80);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (68, 'Urson Riolfi', 'New York Police Department', '2020/09/16', 50, 88);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (69, 'Layney Le Cornu', 'LA Police Department', '2020/12/27', 20, 29);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (70, 'Shellysheldon Grimme', 'Miami Police Department', '2020/01/27', 43, 28);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (71, 'Hill Dallywater', 'Boston Police Department', '2020/10/02', 43, 74);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (72, 'Antonetta Eykel', 'New York Police Department', '2021/08/16', 51, 19);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (73, 'Bobbi Logie', 'LA Police Department', '2020/11/25', 18, 18);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (74, 'Wileen Minall', 'New York Police Department', '2021/07/13', 51, 58);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (75, 'Terence Docwra', 'Miami Police Department', '2021/07/25', 1, 84);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (76, 'Norine Gulleford', 'Boston Police Department', '2020/06/17', 36, 45);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (77, 'Junette Trowill', 'Miami Police Department', '2021/01/08', 24, 34);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (78, 'Keeley Bunford', 'Boston Police Department', '2021/04/07', 24, 37);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (79, 'Libbi Konrad', 'Boston Police Department', '2020/11/14', 69, 13);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (80, 'Prissie Hurlin', 'LA Police Department', '2021/09/11', 28, 66);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (81, 'Elane de Keyser', 'Boston Police Department', '2021/04/07', 28, 84);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (82, 'Lia Clymo', 'New York Police Department', '2021/03/11', 66, 60);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (83, 'Shae Vuittet', 'New York Police Department', '2021/05/04', 22, 85);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (84, 'Scarlett Brosh', 'LA Police Department', '2020/11/19', 22, 44);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (85, 'Jamey Klugman', 'Boston Police Department', '2021/06/02', 38, 25);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (86, 'Archibaldo Munnis', 'LA Police Department', '2020/10/18', 5, 60);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (87, 'Kass Cicculi', 'Boston Police Department', '2021/11/02', 61, 20);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (88, 'Fifine Drohane', 'Miami Police Department', '2020/05/22', 3, 63);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (89, 'Jori Kilmurray', 'LA Police Department', '2020/12/28', 20, 31);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (90, 'Ursola Shipway', 'Miami Police Department', '2020/05/27', 6, 29);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (91, 'Sherrie Goodlad', 'LA Police Department', '2021/11/30', 71, 57);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (92, 'Derrek Lippini', 'LA Police Department', '2020/04/14', 2, 33);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (93, 'Nina Bourthoumieux', 'New York Police Department', '2021/10/17', 83, 86);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (94, 'Janela Merrilees', 'Miami Police Department', '2020/05/10', 82, 25);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (95, 'Amberly Limbrick', 'Miami Police Department', '2021/09/15', 11, 9);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (96, 'Jackson Cure', 'LA Police Department', '2020/06/02', 76, 99);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (97, 'Marabel Coolican', 'LA Police Department', '2021/12/09', 20, 3);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (98, 'Helsa Barnett', 'Boston Police Department', '2020/09/03', 39, 26);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (99, 'Beverly Weekly', 'LA Police Department', '2021/10/10', 80, 19);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (100, 'Martie Jeanin', 'New York Police Department', '2020/03/18', 2, 66);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (101, 'Garvy England', 'New York Police Department', '2020/07/14', 30, 31);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (102, 'Ingrim Layson', 'Boston Police Department', '2021/03/31', 39, 23);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (103, 'Harriette Widdall', 'New York Police Department', '2021/04/04', 31, 77);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (104, 'Priscella MacMychem', 'Miami Police Department', '2020/11/24', 69, 98);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (105, 'Yancy Artus', 'LA Police Department', '2020/03/06', 46, 77);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (106, 'Corbett Ivatt', 'LA Police Department', '2021/12/03', 39, 36);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (107, 'Nolie Windous', 'Miami Police Department', '2021/10/25', 88, 7);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (108, 'Dionysus Tuma', 'Miami Police Department', '2021/05/23', 15, 72);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (109, 'Moore Hallatt', 'Boston Police Department', '2021/11/29', 36, 88);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (110, 'Queenie Laurence', 'Miami Police Department', '2020/02/01', 77, 76);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (111, 'Farrand Threadgill', 'New York Police Department', '2021/06/24', 80, 95);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (112, 'Marni Guichard', 'Miami Police Department', '2021/01/18', 31, 82);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (113, 'Bevin Birchett', 'LA Police Department', '2021/03/12', 9, 38);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (114, 'Raychel Laughrey', 'LA Police Department', '2020/11/13', 67, 64);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (115, 'Fredelia Mitchell', 'New York Police Department', '2021/11/27', 47, 55);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (116, 'Darn Joron', 'Miami Police Department', '2021/02/25', 1, 23);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (117, 'Peirce Fields', 'New York Police Department', '2021/05/19', 77, 21);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (118, 'Cash Smartman', 'Boston Police Department', '2020/07/10', 78, 7);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (119, 'Joya Menezes', 'Boston Police Department', '2020/08/14', 43, 9);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (120, 'Georgeta Anstead', 'Miami Police Department', '2020/12/04', 50, 5);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (121, 'Boony Pacey', 'New York Police Department', '2020/04/30', 81, 16);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (122, 'Adelbert Tripcony', 'Miami Police Department', '2021/02/05', 72, 69);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (123, 'Cristal Sunnex', 'Miami Police Department', '2020/05/12', 25, 44);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (124, 'Lian Fruser', 'LA Police Department', '2020/05/30', 42, 33);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (125, 'Noellyn Tegler', 'Miami Police Department', '2021/07/27', 9, 37);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (126, 'Binnie Freeth', 'Boston Police Department', '2021/10/31', 7, 94);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (127, 'Seka Whales', 'New York Police Department', '2020/11/01', 72, 94);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (128, 'Halette Bridgestock', 'Miami Police Department', '2020/06/30', 75, 8);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (129, 'Fair Elsie', 'Miami Police Department', '2020/01/13', 75, 65);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (130, 'Addia Cuniffe', 'New York Police Department', '2021/11/30', 90, 73);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (131, 'Ramsay Empringham', 'Boston Police Department', '2021/10/02', 87, 93);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (132, 'Orin McArtan', 'New York Police Department', '2021/06/23', 8, 62);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (133, 'Pierson Gullivan', 'Boston Police Department', '2021/03/18', 53, 16);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (134, 'Raynor Verrico', 'New York Police Department', '2021/11/30', 73, 78);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (135, 'Ashley Freire', 'LA Police Department', '2021/06/02', 37, 48);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (136, 'Anny Meachen', 'LA Police Department', '2021/10/17', 8, 49);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (137, 'Julina Shyre', 'Miami Police Department', '2020/08/06', 8, 47);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (138, 'Niki Ellicombe', 'Boston Police Department', '2020/10/10', 67, 11);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (139, 'Bess Stainland', 'New York Police Department', '2020/05/19', 67, 84);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (140, 'Harp Maxweell', 'Miami Police Department', '2020/04/05', 85, 39);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (141, 'Liv Bohills', 'Miami Police Department', '2020/01/23', 34, 79);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (142, 'Zachariah Bonnaire', 'Boston Police Department', '2021/07/01', 31, 56);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (143, 'Cyb Witherow', 'LA Police Department', '2020/03/08', 17, 21);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (144, 'Jessica Bartels-Ellis', 'Miami Police Department', '2020/10/18', 62, 41);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (145, 'Davidson Foukx', 'New York Police Department', '2020/08/30', 79, 55);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (146, 'Pauletta Simanek', 'LA Police Department', '2021/04/21', 32, 53);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (147, 'Stephen McPhail', 'LA Police Department', '2021/01/21', 49, 39);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (148, 'Mikey Cramphorn', 'LA Police Department', '2021/07/12', 52, 98);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (149, 'Reinold Aldham', 'Boston Police Department', '2020/12/20', 82, 88);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (150, 'Gasper Losemann', 'New York Police Department', '2020/10/11', 16, 7);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (151, 'Jesse Halfacre', 'New York Police Department', '2021/09/27', 27, 79);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (152, 'Jereme Hazleton', 'Boston Police Department', '2020/07/24', 71, 28);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (153, 'Annmarie Whellams', 'Boston Police Department', '2020/05/28', 90, 32);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (154, 'Austin Teas', 'New York Police Department', '2021/09/08', 70, 9);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (155, 'Nefen Aldis', 'Miami Police Department', '2021/10/13', 18, 25);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (156, 'Hailey Pariso', 'LA Police Department', '2021/04/18', 54, 62);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (157, 'Mignon Joskowitz', 'Miami Police Department', '2021/05/17', 17, 12);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (158, 'Magnum Matessian', 'Boston Police Department', '2020/08/03', 79, 95);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (159, 'Gabriello Reddings', 'Boston Police Department', '2021/01/21', 84, 88);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (160, 'Kimmie Leander', 'New York Police Department', '2020/10/31', 90, 61);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (161, 'Peter MacGaughy', 'Boston Police Department', '2020/04/14', 54, 86);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (162, 'Cindi Geke', 'Miami Police Department', '2021/07/19', 63, 35);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (163, 'Ibrahim Johnikin', 'Boston Police Department', '2021/08/06', 60, 86);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (164, 'Joete Callender', 'Boston Police Department', '2020/09/21', 27, 6);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (165, 'Eba Crady', 'Miami Police Department', '2020/12/16', 51, 11);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (166, 'Barrie Dunford', 'Miami Police Department', '2020/09/15', 65, 52);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (167, 'Ambros Posnett', 'New York Police Department', '2021/12/06', 17, 91);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (168, 'Marylou Quillinane', 'New York Police Department', '2021/05/13', 65, 96);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (169, 'Cathee Sloy', 'New York Police Department', '2021/01/26', 12, 66);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (170, 'Damian Starrs', 'Boston Police Department', '2020/01/13', 32, 52);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (171, 'Star Klaas', 'Boston Police Department', '2021/11/02', 47, 90);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (172, 'Vaughn Dahlen', 'Miami Police Department', '2020/06/10', 73, 57);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (173, 'Maddie Piotrkowski', 'New York Police Department', '2020/04/15', 64, 76);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (174, 'Bernard McClymond', 'Boston Police Department', '2020/04/22', 78, 48);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (175, 'Curtis Jephcote', 'LA Police Department', '2021/09/30', 57, 90);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (176, 'Saraann Liptrod', 'LA Police Department', '2021/05/12', 45, 42);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (177, 'Quentin Ferries', 'New York Police Department', '2020/10/31', 62, 55);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (178, 'Jillana Hellin', 'New York Police Department', '2021/10/21', 4, 65);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (179, 'Gipsy Haldin', 'Boston Police Department', '2021/02/09', 38, 34);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (180, 'Rocky Boyall', 'New York Police Department', '2021/05/17', 39, 15);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (181, 'Lewie Stallon', 'New York Police Department', '2021/09/11', 36, 65);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (182, 'Betteann Swinbourne', 'New York Police Department', '2020/11/20', 53, 74);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (183, 'Rayner Woodroff', 'Miami Police Department', '2020/01/20', 88, 4);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (184, 'Jesselyn Drayn', 'LA Police Department', '2021/01/24', 48, 14);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (185, 'Flossy Ollie', 'New York Police Department', '2021/09/02', 12, 51);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (186, 'Barney Simionato', 'New York Police Department', '2021/07/30', 61, 53);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (187, 'Kaspar McNiven', 'LA Police Department', '2021/08/28', 60, 23);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (188, 'Lotta Cobelli', 'Boston Police Department', '2020/11/07', 16, 74);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (189, 'Ahmed Hegge', 'LA Police Department', '2020/10/07', 20, 9);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (190, 'Auroora Quarton', 'Miami Police Department', '2020/12/31', 4, 39);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (191, 'Maximilianus Roskrug', 'New York Police Department', '2020/10/04', 55, 36);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (192, 'Fifi Borley', 'Miami Police Department', '2020/02/24', 41, 80);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (193, 'Gusty McGeaney', 'Boston Police Department', '2020/11/12', 31, 19);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (194, 'Mendy Dabnot', 'Miami Police Department', '2020/05/26', 9, 54);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (195, 'Muire Danelut', 'LA Police Department', '2021/10/05', 90, 63);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (196, 'Clementina Viscovi', 'Boston Police Department', '2021/08/11', 27, 73);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (197, 'Berta Alflat', 'New York Police Department', '2020/10/30', 80, 99);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (198, 'Sergeant Dufall', 'LA Police Department', '2020/03/09', 85, 41);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (199, 'Millie Luety', 'Miami Police Department', '2021/03/24', 45, 24);
insert into investigation (id, crime_commissioner, police_department, investigation_start, crime_id, complex_id) values (200, 'Wilhelmina Elcoat', 'Miami Police Department', '2021/06/19', 62, 20);
